import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>
          Welcome to <a href='https://nextjs.org'>Next.js</a>
        </h1>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam, totam ea molestias at aliquam aspernatur perspiciatis rem non accusamus delectus, labore error rerum! Commodi, illo corporis labore quam molestias modi.</p>
      </main>
    </>
  )
}

export default Home